sudo: true
language: haskell
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
matrix:
  include:
  - env: BUILD=stack ARGS=""
    addons:
      apt:
        packages:
          - libgtk2.0-dev
          - libgtk-3-dev
          - libgtksourceview-3.0-dev
          - happy
          - alex

before_install:
- curl -sSL https://get.haskellstack.org/ | sh

install:
  - stack -j 2 setup --no-terminal
  - stack -j 2 build --only-snapshot --no-terminal

script:
  - stack -j 2 build --no-terminal
  - stack -j 2 test --no-terminal
